name: C/C++ Build and Run

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install GTest
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev
    - name: Run build and application
      run: |
        chmod +x ./run_app.sh
        ./run_app.sh WEEK1/best-time-to-buy-and-sell-stock.cpp > output.txt 2>&1 
        cat output.txt # Display the captured output in the logs (optional)
      shell: bash

    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-output
        path: output.txt

    - name: Commit the output back to the repo (write permissions to github actions required)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only on pushes to main
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add output.txt
        git commit -m "Update application output" || echo "No changes to commit" # Avoids error if no changes
        git push