name: C/C++ Build and Run

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install GTest
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev
    - name: Run build and application
      run: |
        chmod +x ./run_app.sh
        ./run_app.sh WEEK1/best-time-to-buy-and-sell-stock.cpp
